site_name: butter-fly
site_url: 'https://yourbutterfly.github.io/note-site/' #不设置将找不到index.html所在目录
repo_name: 'YourButterfly/note-site'
repo_url: 'https://github.com/YourButterfly/note-site.git'


remote_branch: gh-pages
remote_name: origin
nav:
        - 首页: index.md
        - assembly:
            assembly: module/assembly/assembly.md
        - concolic:
                - angr:
                        - angr-introduce: module/angr/introduce.md
                        - CFG: module/angr/cfg.md
                        - DDG: module/angr/ddg.md
                        - fast-questions: module/angr/fast-question.md
                        - program-state: module/angr/program-state.md
                        - sim_action: module/angr/sim_action.md
        - file format:
                - DOT: module/fileformat/dot.md
                - PDF: module/fileformat/pdf.md
        - fuzzing:
            - afl: module/fuzzing/afl.md
            # - asan: module/fuzzing/asan.md
            - GUI: module/fuzzing/gui.md
            - honggfuzz: module/fuzzing/honggfuzz.md
            - libfuzzer: module/fuzzing/libfuzzer.md
        - IOT:
                - binwalk: module/iot/binwalk.md
        - kernel:
            - kernel-debug: module/kernel/kernel-debug.md
            - kernel-kvm: module/kernel/kernel-kvm.md
            - kernel-header: module/kernel/kernel-header.md
            - kernel-hook: module/kernel/kernel-hook.md
        - llvm:
            - pass: module/llvm/pass.md
        - lua:
            - lua: module/lua/lua.md
        - makefile:
            - cmake: module/makefile/cmake.md
        - python:
            - easyfunction: module/python/easyfunction.md
            - flask: module/python/python-flask.md
            - GooglePythonStyleGuide: module/python/GooglePythonStyleGuide.md
            - python-prompt-toolkit: module/python/python-prompt-toolkit.md
        - semmel-ql:
            - CodeQL: module/semmle-ql/codeql.md
        # - virtualization:
        #     - qemu: module/virtualization/qemu.md
        - webs:
            - webs: module/webs/webs.md
        - wireshark:
            - wireshark: module/wireshark/tshark.md
        - others:
            - others: module/others/others.md
theme: 
        name: 'material'
        language: 'zh'
        featuree:
                tabs: true
extra_css:
- 'stylesheets/extra.css'
- 'stylesheets/custom.css'
- 'stylesheets/simpleLightbox.min.css'
extra_javascript:
- 'javascripts/jquery-3.4.1.min.js'
- 'javascripts/simpleLightbox.min.js'
- 'javascripts/custom.js'
# 一些扩展
markdown_extensions:
- markdown.extensions.attr_list # 允许在MarkDown链接/图片后用括号指明任意标签的字段
- admonition
# use dark theme <https://github.com/fmaida/mkdocs-material-dark-theme>
- codehilite:
    guess_lang: False
    use_pygments: True
    noclasses: True
    pygments_style: monokai 
- toc:
    permalink: true
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.tilde
