site_name: butter-fly
site_url: 'https://yourbutterfly.github.io/note-site/' #不设置将找不到index.html所在目录
repo_name: 'YourButterfly/note-site'
repo_url: 'https://github.com/YourButterfly/note-site.git'


remote_branch: gh-pages
remote_name: origin
nav:
        - 文件格式:
                - PDF: module/fileformat/pdf.md
                - DOT: module/fileformat/dot.md
        - 符号执行:
                - angr:
                        - angr-introduce: module/angr/introduce.md
                        - DDG: module/angr/ddg.md
                        - CFG: module/angr/cfg.md
                        - fast-questions: module/angr/fast-question.md
                        - program-state: module/angr/program-state.md
                        - sim_action: module/angr/sim_action.md
        - IOT:
                - binwalk: module/iot/binwalk.md
        - fuzzing:
            - asan: module/fuzzing/asan.md
            - GUI: module/fuzzing/gui.md
            - honggfuzz: module\fuzzing\honggfuzz.md
        - kernel:
            - kernel-header: module/kernel/kernel-header.md
            - kernel-hook: module/kernel/kernel-hook.md
            - kernel-debug: module/kernel/kernel-debug.md
            - kernel-kvm: module/kernel/kernel-kvm.md
        - llvm:
            - pass: module/llvm/pass.md
        - makefile:
            - cmake: module/makefile/cmake.md
        - python:
            - python-prompt-toolkit: module/python/python-prompt-toolkit.md
            - easyfunction: module/python/easyfunction.md
        - virtualization:
            - qemu: module/virtualization/qemu.md
theme: 
        name: 'material'
        language: 'zh'
        featuree:
                tabs: true
        palette:
                primary: 'blue grey'
# 自定义css
extra_css:
- 'stylesheets/custom.css'
- 'stylesheets/simpleLightbox.min.css'
# 自定义js
extra_javascript:
- 'javascripts/jquery-3.4.1.min.js'
- 'javascripts/simpleLightbox.min.js'
- 'javascripts/custom.js'
# 一些扩展
markdown_extensions:
- markdown.extensions.attr_list # 允许在MarkDown链接/图片后用括号指明任意标签的字段
- admonition
- codehilite:
    guess_lang: false
    linenums: false
- toc:
    permalink: true
- footnotes
- meta
- def_list
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.tilde
